### PR TITLE
allow exists can variodic

### PR DESCRIPTION
**Pull request by charsyam**
today, redis changed exists command can be variodic

```
request> exists ab a c
response> :3
```

but this feature just is in unstable.
@manjuraj Does twemproxy prefer to follow unstable branch of redis ? or stable branch?

### CODE REVIEW

**Comment by manjuraj** [comment]
I think we should wait for the command to be supported in stable branch before supporting them in twemproxy.

**Comment by charsyam** [comment]
@manjuraj Yes, I agree with you.That's why I asked you about it :)

**Comment by charsyam** [comment]
@manjuraj Redis 3.0.3 is out. and It contains variadic exists. 
so it's time to merge this feature :)

**Comment by charsyam** [comment]
@manjuraj Please review this :)
(and I just rebase this. not code changed.)
I think we have a problem about current CI testing.

**Comment by charsyam** [comment]
@manjuraj ping Redis already contains variodic :)

**Comment by charsyam** [comment]
@manjuraj ping

**Comment by charsyam** [comment]
ping @manjuraj

**Comment by TysonAndre** [comment]
https://github.com/twitter/twemproxy/pull/599 implements support for many newer redis commands, including this change to exists - I implemented it the same way without seeing this old pr

**Comment by TysonAndre** [comment]
> #599 implements support for many newer redis commands, including this change to exists - I implemented it the same way without seeing this old pr

I was added as an external collaborator this week - #599 was merged.

**Pull request closed without merging**
