### PR TITLE
Support unittest using google-test.

### PR DESCRIPTION
**Pull request by mckelvin**
- Support unittest using google-test.
- test_hashkit as an example.
- enable unittest in travis.

The gtest-1.7.0.zip is downloaded from [googlecode](https://code.google.com/p/googletest/downloads/detail?name=gtest-1.7.0.zip&can=2) , please verify the SHA1 Checksum before merging this PR.

ALSO SEE:
- https://github.com/twitter/twemproxy/issues/197
- https://github.com/twitter/twemproxy/issues/222

### CODE REVIEW

**Comment by mckelvin** [comment]
@idning Please review.

**Comment by idning** [comment]
a little busy recently. will review latter.

**Comment by mckelvin** [comment]
@idning @manjuraj Please review.

**Comment by mckelvin** [comment]
Closing stale PR.

**Pull request closed without merging**
