### PR TITLE
Added Geo Functionality

### PR DESCRIPTION
**Pull request by mahdi-hdi**
New Redis functionality for geo date type now supported:

```
GEOADD
GEODIST
GEOHASH
GEOPOS
GEORADIUS
GEORADIUSBYMEMBER
```

**Mutli bulk array** was implemented in Redis response parser to support response of **GEORADIUS**.

### CODE REVIEW

**Comment by manjuraj** [comment]
@andyqzb ^

**Comment by andyqzb** [comment]
@mahdi-hdi Can you fix your test cases of geo cmd?

**Comment by mahdi-hdi** [comment]
@andyqzb The test cases use redis-py but the problem is that they didn't release GEO functionality yet (lastest version is 2.10.5). So, you must fetch their master branch in case of testing which I prefer don't add it to travis.sh.

**Comment by tlhunter** [comment]
Bump

**Comment by TysonAndre** [comment]
Support for parsing geo commands was added as part of a larger change to add support for many new/updated redis commands based on the latest commands.json published for redis, see 1239ef9e2f14f954b0f5da22369c0d994a347e45 and https://github.com/twitter/twemproxy/pull/599 (etc.)

A more generic approach was also added yesterday to support parsing multi-bulk responses of arbitrary depths and shapes

**Pull request closed without merging**
