### PR TITLE
support nested multibulk reply

### PR DESCRIPTION
**Pull request by charsyam**
@manjuraj This is part of https://github.com/twitter/twemproxy/pull/393

first. I divided it that is only supporting nested multi bulk reply.

after merging this :)

I will PR second of them :)

Thanks for your reivew :)

### CODE REVIEW

**Comment by charsyam** [comment]
@manjuraj ping :)

**Comment by charsyam** [comment]
@manjuraj I fixed bug for parsing nested multibunk reply.
and it passed tests :)

Thanks. :)

**Comment by charsyam** [comment]
@manjuraj ping

**Comment by TysonAndre** [comment]
Support for redis multibulks of arbitrary depth was added in #612 using a different approach - it looks like this PR is no longer necessary.

**Pull request closed without merging**
