### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by pataquets**
Add Dockerfile to enable image building.
Using the official GCC image, latest tag. More info at https://hub.docker.com/_/gcc/

Just adding files, setting working dir and running make instructions.

Build:

```
$ docker build -t twemproxy .
```

Run:

```
$ docker run --rm -it -p [ext_port1:port1] -p [ext_port2:port2] -p [...] -v [your_host_config_yml]:/etc/nutcracker.yml:ro twemproxy -c /etc/nutcracker.yml --verbose=6 [other options...]
```

FYI, there's a still quicker to test, already built image on my Docker Hub. Test it by running:

```
$ docker run --rm -it -p [ext_port1:port1] -p [ext_port2:port2] -p [...] -v [your_host_config_yml]:/etc/nutcracker.yml:ro pataquets/twemproxy  -c /etc/nutcracker.yml --verbose=6 [other options...]
```

Using `--rm` instead of `-d` makes the container not go background and it to be deleted after stop. Should stop by `CTRL+C`'ing it.
In order for the Docker container to connect to external memcached or Redis instances, either them should be contactable as external IPs or hosts or be linked to other previously run Docker containers via Docker's ```--link``` option.

Here it is an example Docker Compose file I'm using (I can submit it with the PR also if you find it useful):
```
redis1:
  image: redis:3.2
  command: --save "" --maxmemory 128mb
  ports:
    - 63791:6379

redis2:
  image: redis:3.2
  command: --save "" --maxmemory 128mb
  ports:
    - 63792:6379

twemproxy:
  image: pataquets/twemproxy
  command: -c /etc/nutcracker.yml --verbose=6
  links:
    - redis1
    - redis2
  ports:
    - 6379:6379
    - 22222:22222
  volumes:
    - ./conf/nutcracker.redis.yml:/etc/nutcracker.yml:ro
```
Notice that it is tuned for two Redis instances (yml file not included, mount yours)

Optional improvement to come (maybe in another issue):
- Create an 'official', based on your repo, automated build at Docker Hub for the image: https://docs.docker.com/docker-hub/builds/ . Just requires a free Docker Hub account and a following a quick 'Create automated build' process. I'll be happy to help on it, if needed.

### CODE REVIEW

**Comment by pataquets** [comment]
Bump.

**Comment by pataquets** [comment]
@manjuraj : ping (since you're the main commiter)

**Comment by tuananh** [comment]
Dynomite has Dockerfile. Maybe we should consider that too. https://github.com/Netflix/dynomite/blob/dev/docker/Dockerfile

Also, we should use Docker multi-stage build to further reduce footprint.

**Comment by tao12345666333** [comment]
Any update on this?

**Comment by pataquets** [comment]
@manjuraj: Anything else needed here?

I've done a quick search, and there are lots of _rogue_ twemproxy public Docker images:
```
$ docker search twemproxy
NAME                          DESCRIPTION                                     STARS               OFFICIAL            AUTOMATED
zapier/twemproxy              Docker image for running twemproxy both with…   5                                       [OK]
anchorfree/twemproxy                                                          3                                       
softonic/twemproxy            Cache proxy                                     2                                       
malexer/twemproxy             A tiny (<6mb) Alpine-based Docker image of t…   1                                       [OK]
yfix/twemproxy                Dockerized twemproxy                            1                                       [OK]
giosg/twemproxy                                                               0                                       
bdossantos/twemproxy          Twemproxy, aka nutcracker is a fast and ligh…   0                                       [OK]
jgoodall/twemproxy            Docker image of twemproxy proxy server in fr…   0                                       [OK]
the40san/twemproxy            twemproxy for docker                            0                                       
ganomede/twemproxy                                                            0                                       [OK]
orimarti/twemproxy-exporter   Prometheus twemproxy exporter                   0                                       
otus/twemproxy                                                                0                                       
tarantool/twemproxy           This is a Docker image with a custom build o…   0                                       [OK]
vimagick/twemproxy            Twemproxy, aka nutcracker is a fast and ligh…   0                                       
bnusunny/twemproxy                                                            0                                       
ianblenke/twemproxy                                                           0                                       [OK]
mattrobenolt/twemproxy        Twemproxy (nutcracker)                          0                                       
phhhoto/twemproxy                                                             0                                       
ruo91/twemproxy               Twitter - Twemproxy                             0                                       [OK]
livelink/twemproxy                                                            0                                       
michaeltigr/twemproxy         Twemproxy                                       0                                       [OK]
dispatchrobot/twemproxy                                                       0                                       
gojektech/twemproxy                                                           0                                       
perlmint/twemproxy            lightweight twemproxy docker image - based o…   0                                       
studossoftware/twemproxy                                                      0                                       
```
Having an official one would be better, IMO.

**Comment by manjuraj** [comment]
Done. Thank you @pataquets!

**Comment by pataquets** [comment]
@manjuraj You're welcome :)
How about publishing an official image built from source on Docker Hub using [Automated Builds](https://docs.docker.com/docker-hub/builds/)? Alternatively, GitHub has also a public Docker image registry in their CI/CD tools. I can file an issue, if needed.
Also, do you think that submitting an example Docker Compose manifest as stated in the OP would be worthwhile? I can send another PR if it's likely to be merged.

**Comment by pataquets** [comment]
@manjuraj Fancy to set up an [Automated Build](https://docs.docker.com/docker-hub/builds/) on Docker Hub? Or any other similar 'source-built' Docker public image as a snapshot and deployable artifact.

**Pull request merged**
